config/routes.rb
Rails.application.routes.draw do

  resources :user_monitors
  mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'
  resources :payments do
    collection do
      get 'make_payment'
    end
  end
  resources :procedures
  resources :gcolors
  resources :mcolors
  resources :materials
  resources :worktypes
  resources :stores

  resources :sales do
    resources :stores

  end
  get '/store/:id' => 'stores#order_sheet', as: :order_sheet

  get '/sale/:id' => 'sales#factura_print'
  get "label_print" => "sales#label_print", as: :label_print
  get "label_print_e3" => "sales#label_print_e3", as: :label_print_e3
  get "label_print_e5" => "sales#label_print_e5", as: :label_print_e5

  get '/payment/:id' => 'payments#receipt_print', as: :receipt_print
  get 'activity/index'

  get 'accountability/index'

  get 'consulta/index'

  resources :suppliers
  get 'prices/home' => 'prices#home'
  get 'prices/show' => 'prices#show'

  post 'update_prices' => 'prices#update_prices', as: :update_prices

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/sessions#new", as: "new_user_registration"
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  get 'admin/index'
  get 'admin/servicios'
  get 'admin/auth'
  get '/order/:id' => 'orders#label_print'

  resources :items

  resources :categories

  get 'reports/index'
  get 'reports/orders_paid'
  get 'reports/orders_unpaid'
  get 'reports/pending_balance'
  get "orders_unpaid_print" => "reports#orders_unpaid_print", as: :orders_unpaid_print, :defaults => { :format => 'pdf' }
  get "orders_paid_print" => "reports#orders_paid_print", as: :orders_paid_print, :defaults => { :format => 'pdf' }
  get "orders_paid_seq_print" => "reports#orders_paid_seq_print", as: :orders_paid_seq_print, :defaults => { :format => 'pdf' }
  
  get "pending_balance_print" => "reports#pending_balance_print", as: :pending_balance_print, :defaults => { :format => 'pdf' }

  devise_for :users
  resources :users_admin, :controller => 'users'
  resources :orders
  resources :clients
  resources :users

  get 'reports/index'
  get 'admin/index'
  get 'welcome/index'
  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items, dependent: :destroy
  validates_uniqueness_of :name

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
.col.s12
  = form_for @category do |f|
    - if @category.errors.any?
      #error_explanation
        %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
        %ul
          - @category.errors.full_messages.each do |msg|
            %li= msg
    .row.card.container.col.s12{:style => "margin: 0 auto;"}
      .input-field{:class => "col s12 s12 s6"}
        = f.label :name, "Categoría"
        = f.text_field :name
    %br
    %br
    .actions.container{:style => "margin: 0 auto;"}
      %button.btn.waves-effect.waves-light{:name => "action", :type => "submit", data: { disable_with: "Procesando..." }}
        %i.material-icons.right save
        Crear
      %a{:href => categories_path, :class => "waves-effect waves-light btn blue"}
        %i.material-icons.right chevron_left
        Volver

app/views/categories/edit.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Editar Item
  %br
  = render 'form'


-# = link_to 'Show', @item
-# \|
-# = link_to 'Back', items_path
= render :partial => 'layouts/footer'
-# END OF FOOTER

app/views/categories/index.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Listado de Categorías
  %br

  .container{:style => "margin: 0 auto;"}
    %a{:href => new_category_path, :class => "waves-effect waves-light btn blue"}
      %i.material-icons.right add
      Nueva Categoría
  %br
  .card.container{:style => "margin: 0 auto;"}
    %table
      %thead
        %tr
          %th Categoría
          %th
          %th
          %th

      %tbody
        - @categories.each do |category|
          %tr
            %td= category.name
            %td= link_to 'Ver', category
            %td= link_to 'Editar', edit_category_path(category)
            %td= link_to 'Eliminar', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br

    -# = link_to 'New Category', new_category_path


= render :partial => 'layouts/footer'
-# END OF FOOTER

app/views/categories/new.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Nuevo Servicio
  %br

  = render 'form'

-# = link_to 'Back', categories_path





= render :partial => 'layouts/footer'
-# END OF FOOTER

app/views/categories/show.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Detalles
  %br

  .card.container{:style => "margin: 0 auto;"}
    %p
      %b Categoría:
      = @category.name

    = link_to 'Edit', edit_category_path(@category)
    \|
    = link_to 'Volver', categories_path



= render :partial => 'layouts/footer'
-# END OF FOOTER