config/routes.rb
Rails.application.routes.draw do

  resources :user_monitors
  mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'
  resources :payments do
    collection do
      get 'make_payment'
    end
  end
  resources :procedures
  resources :gcolors
  resources :mcolors
  resources :materials
  resources :worktypes
  resources :stores

  resources :sales do
    resources :stores

  end
  get '/store/:id' => 'stores#order_sheet', as: :order_sheet

  get '/sale/:id' => 'sales#factura_print'
  get "label_print" => "sales#label_print", as: :label_print
  get "label_print_e3" => "sales#label_print_e3", as: :label_print_e3
  get "label_print_e5" => "sales#label_print_e5", as: :label_print_e5

  get '/payment/:id' => 'payments#receipt_print', as: :receipt_print
  get 'activity/index'

  get 'accountability/index'

  get 'consulta/index'

  resources :suppliers
  get 'prices/home' => 'prices#home'
  get 'prices/show' => 'prices#show'

  post 'update_prices' => 'prices#update_prices', as: :update_prices

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/sessions#new", as: "new_user_registration"
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  get 'admin/index'
  get 'admin/servicios'
  get 'admin/auth'
  get '/order/:id' => 'orders#label_print'

  resources :items

  resources :categories

  get 'reports/index'
  get 'reports/orders_paid'
  get 'reports/orders_unpaid'
  get 'reports/pending_balance'
  get "orders_unpaid_print" => "reports#orders_unpaid_print", as: :orders_unpaid_print, :defaults => { :format => 'pdf' }
  get "orders_paid_print" => "reports#orders_paid_print", as: :orders_paid_print, :defaults => { :format => 'pdf' }
  get "orders_paid_seq_print" => "reports#orders_paid_seq_print", as: :orders_paid_seq_print, :defaults => { :format => 'pdf' }
  
  get "pending_balance_print" => "reports#pending_balance_print", as: :pending_balance_print, :defaults => { :format => 'pdf' }

  devise_for :users
  resources :users_admin, :controller => 'users'
  resources :orders
  resources :clients
  resources :users

  get 'reports/index'
  get 'admin/index'
  get 'welcome/index'
  root 'welcome#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :client
  has_one :invoice_number
  has_many :stores, dependent: :destroy
  has_many :payments, dependent: :destroy
  validates :patient_name, :presence => true
  validates :client_id, :presence => true
  # validates :order_date, :presence => true
  attr_accessor :client_email

  accepts_nested_attributes_for :stores, allow_destroy: true
  accepts_nested_attributes_for :payments, allow_destroy: true

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :set_discount, only: [:show, :edit, :update, :destroy]
  # before_action :set_total, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    # @sales = Sale.all
    @search = Sale.ransack(params[:q])
    @sales = @search.result.page(params[:page]).per_page(15)

  end

# Label de 6'' (2.4 '' x 7.2'')
  def label_print
    @sale = Sale.find(params[:sale_id])
    respond_to do |format|
      format.html
      format.pdf do
      pdf = LabelPdf.new(@sale)
      send_data pdf.render,
        filename: "Label_Orden_#{@sale.id}.pdf",
        type: "application/pdf",
        disposition: "inline" ##display in browser
      end
    end
  end

  # Label de 3'' (2.4'' x 3.9'')
    def label_print_e3
      @sale = Sale.find(params[:sale_id])
      respond_to do |format|
        format.html
        format.pdf do
        pdf = LabelPdfE3.new(@sale)
        send_data pdf.render,
          filename: "Label_Orden_#{@sale.id}.pdf",
          type: "application/pdf",
          disposition: "inline" ##display in browser
        end
      end
    end


    # Label de 0.5'' (2.4'' x 1.1'')
      def label_print_e5
        @sale = Sale.find(params[:sale_id])
        respond_to do |format|
          format.html
          format.pdf do
          pdf = LabelPdfE5.new(@sale)
          send_data pdf.render,
            filename: "Label_Orden_#{@sale.id}.pdf",
            type: "application/pdf",
            disposition: "inline" ##display in browser
          end
        end
      end





  def factura_print
    @sale = Sale.find(params[:id])
    if @sale.invoice_date == nil
      @sale.invoice_date = Time.now
    end
    respond_to do |format|
      format.html
      format.pdf do
      # Generar @order.invoice_num aqui
      # byebug
      if @sale.invoice_number.nil?
        invoice_number = @sale.invoice_number || @sale.create_invoice_number
        invoice_number.increment!
        # byebug
        @sale.invoice_num = invoice_number.id
        @sale.save
      end
      @sale.save
      pdf = FacturaPdf.new(@sale)
      send_data pdf.render,
        filename: "factura_#{@sale.id}.pdf",
        type: "application/pdf",
        disposition: "inline" ##display in browser
      end
    end
  end





  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @clients = Client.all

    if params[:client]
      @client = Client.find(params[:client])
    end
  end

  # GET /sales/1/edit
  def edit
    @clients = Client.all

  end

  # POST /sales
  # POST /sales.json
  def create
    @clients = Client.all
    @sale = Sale.new(sale_params)



    if @sale.coti
      @sale.state = "Cotizacion"
    end

    respond_to do |format|
      if @sale.save
        UserMonitor.create(user: current_user.id, info: "Ha agregado Nueva Orden ##{@sale.id}")
        format.html { redirect_to @sale, notice: 'Orden Salvada Correctamente.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end




  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    unless  params[:sale][:state] == "cotizacion"
      @sale.coti = false
    end



    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'La Orden fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_discount
    @sale.discount_amount = @sale.total_amount*(@sale.discount/100)
    @sale.save
  end

  def set_total
    @sale.total_amount = @sale.total_amount - @sale.discount_amount
    @sale.save
  end


  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale_d_id = @sale.id
    @sale.destroy

    respond_to do |format|
      UserMonitor.create(user: current_user.id, info: "Ha Eliminado Orden ##{sale_d_id}")
      format.html { redirect_to sales_url, notice: 'La Orden fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:patient_name, :age, :sex, :order_date,
                                   :client_note, :other_note, :coti, :state,
                                   :concept, :invoice_num, :invoice_date, :paid_status, :total_amount, :discount, :discount_amount,
                                   :order_total, :remaining_amount, :client_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.haml
= form_for @sale do |f|
  - if @sale.errors.any?
    - flash[:notice] = "Orden no pudo ser procesada, favor llenar los campos correctamente"

  .row.card.container.col.s12{:style => "margin: 0 auto;"}
    .right{:style => "padding-right:15px;"}
      .input-fields.right
        %br
        = f.check_box :coti
        = f.label :coti, "Cotización"
    %br
    %br

    .input-field{:class => "col s12 m6", :style => "margin-top: 0px;"}
      -# = f.label :client
      -# = f.text_field :client
      -# = f.select(:client_id, @clients.collect {|p| [ p.name, p.id ] }, {include_blank: false, prompt: 'Seleccionar Cliente'}, :id => "e1", :class => "js-example-responsive", :style => "width: 100%;")
      - if params[:client]
        = f.label "Cliente: #{Client.find(params[:client]).name}"
        = f.hidden_field :client_id, value: params[:client]
      - else
        = f.select(:client_id, @clients.collect {|p| [ p.name, p.id ] }, {include_blank: false, prompt: 'Seleccionar Cliente'}, :id => "e1", :class => "js-example-responsive", :style => "width: 100%;")

    - 3.times do
      %br
    %hr.style17
    .input-field{:class => "col s12 m6"}
      %i.material-icons.prefix account_circle
      = f.label :patient_name, "Paciente"
      = f.text_field :patient_name

    .input-field{:class => "col s12 m6 s12"}
      %i.material-icons.prefix perm_identity
      = f.label :age, "Edad"
      = f.number_field :age

    -# .input-field{:class => "col s12 m6"}
    .col.s12.m6
      %i.material-icons.prefix tag_faces
      = f.radio_button :sex, 'Femenino'
      = f.label :sex, 'Femenino', :value => 'Femenino'
      
      = f.radio_button :sex, 'Masculino'
      = f.label :sex, 'Masculino', :value => 'Masculino'

    .input-field{:class => "col s12 m6 s12"}
      %i.material-icons.prefix today
      = f.label :order_date, "Fecha de Entrega"
      = f.text_field :order_date,
        :class => "datepicker"



    %div.col.s12
      .input-field.col.s6#textarea1
        %i.material-icons.prefix mode_edit
        = f.label :client_note, "Notas del Cliente"
        = f.text_area :client_note,
          :class => "materialize-textarea"

      .input-field.col.s6
        %i.material-icons.prefix mode_edit
        = f.label :other_note, "Otras Notas"
        = f.text_area :other_note,
          :class => "materialize-textarea"

    -# .input-field
    -#   = f.label :coti
    -#   = f.check_box :coti
    -# .input-field
    -#   = f.label :state
    -#   = f.text_field :state
    -# .input-field
    -#   = f.label :concept
    -#   = f.text_field :concept
  %br
  %br
  .actions.container{:style => "margin: 0 auto;"}
    -# = f.submit 'Save'
    %button.btn.waves-effect.waves-light.right#order_submit{:name => "action", :type => "submit", data: { disable_with: "Procesando.." }}
      %i.material-icons.right save
      Salvar

app/views/sales/_order_status.html.haml

.col.s3.right
  -# = @sale.paid_status
  -case @sale.state.capitalize
    -when "En proceso"
      .chip.in_process= @sale.state.capitalize
    -when "Urgente"
      .chip.in_urgent= @sale.state.capitalize
    -when "En prueba"
      .chip.in_test_pending= @sale.state.capitalize
    -when "Facturada - pendiente"
      .chip.in_test_invoiced= @sale.state.capitalize
    -when "Facturada - pago"
      .chip.in_paid= @sale.state.capitalize
    -when "Anulada"
      .chip.in_null#sale_null= @sale.state.capitalize
    -when "Cotizacion"
      .chip.in_null= @sale.state.capitalize
-#- case @sale.coti
-#  -when true
-#    .p.left{:style => "color: red;"} Cotizacion

app/views/sales/edit.html.haml
-# %h1 Editar Orden
-#

%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br


  -# %br
  -# %h3.container{:style => "margin: 0 auto;"} Nueva Orden
  -# %br
  %h3{:style => "margin: 0 auto; text-align: center;"}
    = image_tag "eu-tooth.png", :style => "width: 80px;"

  = render 'form'

  -# = link_to 'Show', @sale
  -# \|
  -# = link_to 'Back', sales_path

-# = link_to 'Back', sales_path
-#

= render :partial => 'layouts/footer'
-# END OF FOOTER

app/views/sales/index.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Listado de Ordenes
  %br

  .container{:style => "margin: 0 auto;"}
    %a{:href => new_sale_path, :class => "waves-effect waves-light btn blue"}
      %i.material-icons.right add
      Nueva Orden
    %a.right.modal-trigger{:href =>"#search_filter_orders", :class => "waves-effect waves-light btn blue"}
      %i.material-icons.right search
      Filtro

  .row.card.container.modal#search_filter_orders{:style => "width: 800px; height:900px;"}
    = search_form_for @search, url: sales_path do |f|
      .input-field{:class => "col s6"}
        = f.label :client_name_cont, "Cliente"
        = f.text_field :client_name_cont
      .input-field{:class => "col s6"}
        = f.label :patient_name_cont, "Paciente"
        = f.text_field :patient_name_cont
      .input-field{:class => "col s3"}
        = f.label :created_at_date_gequals, "Desde"
        = f.text_field :created_at_date_gequals,
                       :class => "datepicker_all"
      .input-field{:class => "col s3"}
        = f.label :created_at_date_lequals, "Hasta"
        = f.text_field :created_at_date_lequals,
                       :class => "datepicker_all"
      .input-field.col.s6
        = f.select( :state_cont, options_for_select([[""],
                                                ["En Proceso", {class: 'circle'}],
                                                ["Urgente", {class: 'circle'}],
                                                ["En Prueba", {class: 'circle'}],
                                                ["Facturada - Pendiente", {class: 'circle'}],
                                                ["Facturada - Pago", {class: 'circle'}],
                                                ["Anulada", {class: 'circle'}]],
                                                disabled: "Elige el Estado"), class: "browser-default" )

      -#"data-icon" => "/assets/blue.png"
      
      -#.input-field.col.s6
      -#  %select.icons
      -#    %option{:disabled => "disabled", :selected => "selected", :value => ""} Elige el Estado
      -#    %option.circle{:value => "1", "data-icon" => "/assets/blue.png"} En Proceso
      -#    %option.circle{:value => "2", "data-icon" => "/assets/red.png"} Urgente
      -#    %option.circle{:value => "3", "data-icon" => "/assets/orange.png"} En Prueba
      -#    %option.circle{:value => "4", "data-icon" => "/assets/orange.png"} Facturada - Pendiente
      -#    %option.circle{:value => "5", "data-icon" => "/assets/green.png"} Facturada - Pago
      -#    %option.circle{:value => "6", "data-icon" => "/assets/null.png"} Anulada
      -#  %label Estado



      = f.submit "Buscar", :class => "waves-effect waves-light btn blue",
                            :style => "left: 15px; bottom: 5px;"


  %br


  .row.container.card{:style => "margin: 0 auto;"}
    %table.centered.highlight#table_line
      %thead
        %tr
          %th Cliente
          %th Paciente
          %th Fecha  de Entrada
          %th Fecha  de Entrega
          %th Estado
          %th
          %th
          %th
          %th

      %tbody
        - @sales.each do |sale|
          %tr
            %td= sale.client.name
            %td= sale.patient_name
            %td= sale.created_at.strftime("%d/%m/%Y")
            %td= sale.order_date.strftime("%d/%m/%Y") if sale.order_date != nil
            - case sale.state.capitalize
              -when "En proceso"
                %td.chip.in_process{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize
              -when "Urgente"
                %td.chip.in_urgent{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize
              -when "En prueba"
                %td.chip.in_test_pending{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize
              -when "Facturada - pendiente"
                %td.chip.in_test_pending{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize
              -when "Facturada - pago"
                %td.chip.in_paid{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize
              -when "Anulada"
                %td.chip.in_null{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize
              -when "Cotizacion"
                %td.chip.in_null{:style => "margin: 5px auto 5px 5px; display: block;"}= sale.state.capitalize



            %td.btn-group
              %a{:href => sale_path(sale), :class => "waves-effect waves-light btn-floating blue tooltipped", "data-tooltip" => "Ver", "data-position" => "top"}
                %i.material-icons.right search
              - if current_user.role_level == 1
                -#%a{:href => edit_order_path(order), :class => "waves-effect waves-light btn-floating teal tooltipped", "data-tooltip" => "Editar", "data-position" => "top"}
                -#  %i.material-icons.right mode_edit
                -# %button.btn.btn-floating.red.btn-sm.tooltipped{:type => "button", "data-tooltip" => "Eliminar", "data-position" => "right"}
                -#   = link_to 'X', sale_path(sale), :method => :delete, :style => "color: white;"

            -# %td= link_to 'Show', sale
            -# %td= link_to 'Edit', edit_sale_path(sale)
            -# %td= link_to 'Destroy', sale, :method => :delete, :data => { :confirm => 'Are you sure?' }

    %br
    %ul.pagination.right{:style => "margin: 0 auto; text-align: right;"}
      = will_paginate @sales


  -#= link_to 'New Sale', new_sale_path

-# END OF MAIN

-# FOOTER

%footer.page-footer
  = render :partial => 'layouts/footer'
-# END OF FOOTER

app/views/sales/new.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br


  -# %br
  -# %h3.container{:style => "margin: 0 auto;"} Nueva Orden
  -# %br


  %h3{:style => "margin: 0 auto; text-align: center;"}
    = image_tag "eu-tooth.png", :style => "width: 80px;"

  = render 'form'

-# = link_to 'Back', sales_path
-#

= render :partial => 'layouts/footer'
-# END OF FOOTER