config/routes.rb
Rails.application.routes.draw do

  resources :user_monitors
  mount RailsAdmin::Engine => '/admin_panel', as: 'rails_admin'
  resources :payments do
    collection do
      get 'make_payment'
    end
  end
  resources :procedures
  resources :gcolors
  resources :mcolors
  resources :materials
  resources :worktypes
  resources :stores

  resources :sales do
    resources :stores

  end
  get '/store/:id' => 'stores#order_sheet', as: :order_sheet

  get '/sale/:id' => 'sales#factura_print'
  get "label_print" => "sales#label_print", as: :label_print
  get "label_print_e3" => "sales#label_print_e3", as: :label_print_e3
  get "label_print_e5" => "sales#label_print_e5", as: :label_print_e5

  get '/payment/:id' => 'payments#receipt_print', as: :receipt_print
  get 'activity/index'

  get 'accountability/index'

  get 'consulta/index'

  resources :suppliers
  get 'prices/home' => 'prices#home'
  get 'prices/show' => 'prices#show'

  post 'update_prices' => 'prices#update_prices', as: :update_prices

  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "/sign_up" => "devise/sessions#new", as: "new_user_registration"
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end

  get 'admin/index'
  get 'admin/servicios'
  get 'admin/auth'
  get '/order/:id' => 'orders#label_print'

  resources :items

  resources :categories

  get 'reports/index'
  get 'reports/orders_paid'
  get 'reports/orders_unpaid'
  get 'reports/pending_balance'
  get "orders_unpaid_print" => "reports#orders_unpaid_print", as: :orders_unpaid_print, :defaults => { :format => 'pdf' }
  get "orders_paid_print" => "reports#orders_paid_print", as: :orders_paid_print, :defaults => { :format => 'pdf' }
  get "orders_paid_seq_print" => "reports#orders_paid_seq_print", as: :orders_paid_seq_print, :defaults => { :format => 'pdf' }
  
  get "pending_balance_print" => "reports#pending_balance_print", as: :pending_balance_print, :defaults => { :format => 'pdf' }

  devise_for :users
  resources :users_admin, :controller => 'users'
  resources :orders
  resources :clients
  resources :users

  get 'reports/index'
  get 'admin/index'
  get 'welcome/index'
  root 'welcome#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def orders_unpaid
    # @sales = Sale.all
    @search = Sale.where(:paid_status => false).ransack(params[:q])
    @sales = @search.result.page(params[:page]).per_page(30).order('invoice_date DESC')


  end

  def orders_paid
    # @sales = Sale.all
    @search = Sale.includes(:invoice_number).where(:paid_status => true).ransack(params[:q])
    @sales = @search.result.page(params[:page]).per_page(30).order('invoice_date DESC')
    # byebug
  end

  def orders_paid_seq
    @search = Sale.joins(:invoice_number).merge(InvoiceNumber.order(id: :asc)).where(:paid_status => true).ransack(params[:q])
    @sales = @search.result.page(params[:page]).per_page(30)
    # byebug
  end

  def pending_balance
    # @sales = Sale.all
    # @clients = Client.all
    @search = Sale.where(:paid_status => false).ransack(params[:q])
    @sales = @search.result.page(params[:page]).per_page(30).order('invoice_date DESC')
  end

  # opcion imprimir reporte en secuencia 


  def orders_unpaid_print
    @search = Sale.where(:paid_status => false).ransack(params[:q])
    @sales = @search.result.page(params[:page]).order('invoice_date DESC')

    @from = params[:q][:created_at_date_gequals]
    @to = params[:q][:created_at_date_lequals]

    respond_to do |format|
      # format.html
      format.pdf do
      pdf = ReportUnpaid.new(@sales,@from,@to)
      send_data pdf.render,
        filename: "OrdenesPorPagar_#{@from}_#{@to}.pdf",
        type: "application/pdf",
        disposition: "inline" ##display in browser
      end
    end
  end

  def orders_paid_print
    @from = params[:q][:created_at_date_gequals]
    @to = params[:q][:created_at_date_lequals]
    # @search = Sale.includes(:payments).where(:paid_status => true)
    @search = Sale.includes(:payments).where(:paid_status => true).where("payments.paydate >= ?", @from)
    # @search = Sale.joins(:payments).merge(Payment.order(created_at: :ASC)).where(:paid_status => true).ransack(params[:q])
    # byebug
    @sales = @search.order('payments.paydate DESC')
    # @sales = @search.result.order('order_total DESC')
    # byebug
    # @sales = @search.where("exists (select payments.id from payments where created_at >= ? AND created_at <= ?)", @from, @to)
    # byebug


    respond_to do |format|
      # format.html
      format.pdf do
      pdf = ReportBalance.new(@sales,@from,@to)
      send_data pdf.render,
        filename: "OrdenesConsolidadas_#{@from}_#{@to}.pdf",
        type: "application/pdf",
        disposition: "inline" ##display in browser
      end
    end
  end

  def orders_paid_seq_print
    @search = Sale.joins(:invoice_number).merge(InvoiceNumber.order(id: :asc)).where(:paid_status => true).ransack(params[:q])
    @sales = @search.result

    @from = params[:q][:created_at_date_gequals]
    @to = params[:q][:created_at_date_lequals]

    respond_to do |format|
      # format.html
      format.pdf do
      pdf = ReportBalance.new(@sales,@from,@to)
      send_data pdf.render,
        filename: "OrdenesConsolidadasSecuencia_#{@from}_#{@to}.pdf",
        type: "application/pdf",
        disposition: "inline" ##display in browser
      end
    end
  end



  def pending_balance_print
    @search = Sale.where(:paid_status => false).ransack(params[:q])
    @sales = @search.result.page(params[:page])

    @from = params[:q][:created_at_date_gequals]
    @to = params[:q][:created_at_date_lequals]

    respond_to do |format|
      # format.html
      format.pdf do
      pdf = ReportBalance.new(@sales,@from,@to)
      send_data pdf.render,
        filename: "BalancePendientes#{@from}_#{@to}.pdf",
        type: "application/pdf",
        disposition: "inline" ##display in browser
      end
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'

  -# CONTENT

  -# %div{:style => "width:90%; margin: 0 auto;transform: scale(1.0);"}
  -#   = render :partial => 'layouts/tooth_chart'

  %br
  %h3{:style => "margin: 0 auto; text-align: center;"}
    %i.material-icons{:style => "margin: 8px; font-size:46px;"} equalizer
    Reportes
  %br







  .row.col.m12.container{:style => "margin: 0 auto;"}
    .col.s6{:style => "width: 426.66px;"}
      .card
        .card-image
          =image_tag "summary-forms.jpg", :style => "height: 161.469px;"
          -# %span.card-title Report Title
        .card-content
          %p
            Ordenes Por Pagar
        .card-action
          %a{:href => reports_orders_unpaid_path} Consultar
    .col.s6{:style => "width: 426.66px;"}
      .card
        .card-image
          =image_tag "papers.jpg", :style => "height: 161.469px;"
          -# %span.card-title Report Title
        .card-content
          %p
            Ordenes Consolidadas
        .card-action
          %a{:href => reports_orders_paid_path} Consultar
    -# .col.s12.m7{:style => "width: 426.66px;"}
    -#   .card
    -#     .card-image
    -#       =image_tag "pendingbalance.jpg", :style => "height: 161.469px;"
    -#       -# %span.card-title Report Title
    -#     .card-content
    -#       %p
    -#         Reporte de Balances pendientes
    -#     .card-action
    -#       %a{:href => reports_pending_balance_path} Consultar






-# END OF MAIN

-# FOOTER

%footer.page-footer
  = render :partial => 'layouts/footer'
-# END OF FOOTER

app/views/reports/orders_paid.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Reporte de Ordenes Consolidadas
  %br


  .container{:style => "margin: 0 auto;"}
    .card.row
      = search_form_for @search, url: orders_paid_print_path, :html => {:target=>'_blank'} do |k|
        .input-field{:class => "col s6"}
          = k.label :client_name_cont, "Cliente"
          = k.text_field :client_name_cont
        .input-field{:class => "col s3"}
          = k.label :created_at_date_gequals, "Desde"
          = k.text_field :created_at_date_gequals,
                         :class => "datepicker_all"
        -# .input-field{:class => "col s3"}
        -#   = k.label :created_at_date_lequals, "Hasta"
        -#   = k.text_field :created_at_date_lequals,
        -#                  :class => "datepicker_all"

        = k.submit "Imprimir Por Fecha de Pago", :class => "waves-effect waves-light btn",
                               :style => "left: 15px; bottom: 5px;"

      
      = search_form_for @search, url: orders_paid_seq_print_path, :html => {:target=>'_blank'} do |k|
        .input-field{:class => "col s6"}
          = k.label :client_name_cont, "Cliente"
          = k.text_field :client_name_cont
        .input-field{:class => "col s3"}
          = k.label :created_at_date_gequals, "Desde"
          = k.text_field :created_at_date_gequals,
                        :class => "datepicker_all"
        .input-field{:class => "col s3"}
          = k.label :created_at_date_lequals, "Hasta"
          = k.text_field :created_at_date_lequals,
                        :class => "datepicker_all"

        = k.submit "Imprimir en Secuencia", :class => "waves-effect waves-light btn",
                              :style => "left: 15px; bottom: 5px;"


    %a.modal-trigger{:href =>"#search_filter_orders", :class => "waves-effect waves-light btn blue"}
      %i.material-icons.right search
      Filtro


  .row.card.container.modal#search_filter_orders{:style => "width: 800px; height:900px;"}
    = search_form_for @search, url: reports_orders_paid_path do |f|
      .input-field{:class => "col s6"}
        = f.label :client_name_cont, "Cliente"
        = f.text_field :client_name_cont
      .input-field{:class => "col s3"}
        = f.label :created_at_date_gequals, "Desde"
        = f.text_field :created_at_date_gequals,
                       :class => "datepicker_all"
      .input-field{:class => "col s3"}
        = f.label :created_at_date_lequals, "Hasta"
        = f.text_field :created_at_date_lequals,
                       :class => "datepicker_all"

        = f.submit "Buscar", :class => "waves-effect waves-light btn blue",
                              :style => "left: 15px; bottom: 5px;"


  %br




  .row.container.card{:style => "margin: 0 auto; width: 80%;"}
    %table.centered.highlight#orders_t
      %thead
        %tr
          %th No. Factura
          %th Cliente
          %th Paciente
          %th Orden No.
          %th Fecha de Entrada 
          %th Fecha de Pago
          -#%th Fecha  de Entrega
          -# %th Estado
          %th Monto RD$
          -# %th Balance RD$
          -# %th Nota Del Cliente
          -# %th Otras Notas
          %th Ver



      %tbody
        - @sales.each do |sale|
          - unless sale.invoice_number == nil
            %tr
              %td= sale.invoice_number.id
              %td= sale.client.name
              %td= sale.patient_name
              %td= sale.id
              %td= sale.created_at.strftime("%d/%m/%Y")
              %td= sale.payments.last.paydate.strftime("%d/%m/%Y")  
              -#%td= order.order_date
              -# %td= sale.state
              %td= "$#{number_to_currency(sale.order_total - sale.discount_amount, :format => "%u%n", :unit => '',:delimiter => ',',:separator => '.')}"
              -# %td= "$#{number_to_currency(sale.remaining_amount - sale.discount_amount, :format => "%u%n", :unit => '',:delimiter => ',',:separator => '.')}"
              %td.btn-group
                %a{:href => sale_path(sale), :class => "waves-effect waves-light btn-floating blue tooltipped", "data-tooltip" => "Ver", "data-position" => "top"}
                  %i.material-icons.right search



        %br
        .div
        %ul.pagination.right{:style => "margin: 0 auto;"}
          = will_paginate @sales

  -# %td= order.client_note
            -# %td= order.other_note



      -# %br
      -# .div
      -#   %ul.pagination{:style => "margin: 0 auto; text-align: right;"}
      -#     %li.disabled
      -#       %a{:href => "#!"}
      -#         %i.material-icons chevron_left
      -#     %li.active
      -#       %a{:href => "#!"} 1
      -#     %li.waves-effect
      -#       %a{:href => "#!"} 2
      -#     %li.waves-effect
      -#       %a{:href => "#!"} 3
      -#     %li.waves-effect
      -#       %a{:href => "#!"}
      -#         %i.material-icons chevron_right

  %br


  -# END OF MAIN

  -# FOOTER

  %footer.page-footer
    = render :partial => 'layouts/footer'
  -# END OF FOOTER

app/views/reports/orders_unpaid.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Reporte de Ordenes x Pagar
  %br


  .container{:style => "margin: 0 auto;"}
    .card.row
      = search_form_for @search, url: orders_unpaid_print_path, :html => {:target=>'_blank'} do |k|
        .input-field{:class => "col s6"}
          = k.label :client_name_cont, "Cliente"
          = k.text_field :client_name_cont
        .input-field{:class => "col s3"}
          = k.label :created_at_date_gequals, "Desde"
          = k.text_field :created_at_date_gequals,
                         :class => "datepicker_all"
        .input-field{:class => "col s3"}
          = k.label :created_at_date_lequals, "Hasta"
          = k.text_field :created_at_date_lequals,
                         :class => "datepicker_all"

        = k.submit "Imprimir", :class => "waves-effect waves-light btn",
                               :style => "left: 15px; bottom: 5px;"



    %br
    %a.modal-trigger{:href =>"#search_filter_orders", :class => "waves-effect waves-light btn blue"}
      %i.material-icons.right search
      Filtro


  .row.card.container.modal#search_filter_orders{:style => "width: 800px; height:900px;"}
    = search_form_for @search, url: reports_orders_unpaid_path do |f|
      .input-field{:class => "col s6"}
        = f.label :client_name_cont, "Cliente"
        = f.text_field :client_name_cont
      .input-field{:class => "col s3"}
        = f.label :created_at_date_gequals, "Desde"
        = f.text_field :created_at_date_gequals,
                       :class => "datepicker_all"
      .input-field{:class => "col s3"}
        = f.label :created_at_date_lequals, "Hasta"
        = f.text_field :created_at_date_lequals,
                       :class => "datepicker_all"

        = f.submit "Buscar", :class => "waves-effect waves-light btn blue",
                              :style => "left: 15px; bottom: 5px;"


  %br

  .container.card{:style => "margin: 0 auto;"}
    %table.centered.highlight#orders_t
      %thead
        %tr
          %th Orden No.
          %th Cliente
          %th Paciente
          %th No. Factura
          %th Fecha  de Entrada
          -#%th Fecha  de Entrega
          %th Estado
          %th Monto RD$
          %th Balance RD$
          -# %th Nota Del Cliente
          -# %th Otras Notas
          %th Ver



      %tbody
        - @sales.each do |sale|
          - unless sale.invoice_number == nil
            %tr
              %td= sale.id
              %td= sale.client.name
              %td= sale.patient_name
              %td= sale.invoice_number.id
              %td= sale.created_at.strftime("%d/%m/%Y")
              -#%td= order.order_date
              %td= sale.state
              %td= "$#{number_to_currency(sale.order_total - sale.discount_amount, :format => "%u%n", :unit => '',:delimiter => ',',:separator => '.')}"
              %td= "$#{number_to_currency(sale.remaining_amount - sale.discount_amount, :format => "%u%n", :unit => '',:delimiter => ',',:separator => '.')}"
              %td.btn-group
                %a{:href => sale_path(sale), :class => "waves-effect waves-light btn-floating blue tooltipped", "data-tooltip" => "Ver", "data-position" => "top"}
                  %i.material-icons.right search

        %br
        .div
        %ul.pagination.right{:style => "margin: 0 auto;"}
          = will_paginate @sales


  -# %td= order.client_note
            -# %td= order.other_note



      -# %br
      -# .div
      -#   %ul.pagination{:style => "margin: 0 auto; text-align: right;"}
      -#     %li.disabled
      -#       %a{:href => "#!"}
      -#         %i.material-icons chevron_left
      -#     %li.active
      -#       %a{:href => "#!"} 1
      -#     %li.waves-effect
      -#       %a{:href => "#!"} 2
      -#     %li.waves-effect
      -#       %a{:href => "#!"} 3
      -#     %li.waves-effect
      -#       %a{:href => "#!"}
      -#         %i.material-icons chevron_right

  %br


  -# = link_to 'New Order', new_order_path
  -# END OF MAIN

  -# FOOTER

  %footer.page-footer
    = render :partial => 'layouts/footer'
  -# END OF FOOTER

app/views/reports/pending_balance.html.haml
%header

-# MAIN

%main
  = render :partial => 'layouts/top_navbar'
  %br
  %h3.container{:style => "margin: 0 auto;"} Reporte de Balances pendientes
  %br


  .container{:style => "margin: 0 auto;"}
    .card.row
      = search_form_for @search, url: pending_balance_print_path, :html => {:target=>'_blank'} do |k|
        .input-field{:class => "col s6"}
          = k.label :client_name_cont, "Cliente"
          = k.text_field :client_name_cont
        .input-field{:class => "col s3"}
          = k.label :created_at_date_gequals, "Desde"
          = k.text_field :created_at_date_gequals,
                         :class => "datepicker_all"
        .input-field{:class => "col s3"}
          = k.label :created_at_date_lequals, "Hasta"
          = k.text_field :created_at_date_lequals,
                         :class => "datepicker_all"

        = k.submit "Imprimir", :class => "waves-effect waves-light btn",
                               :style => "left: 15px; bottom: 5px;"
    %a.modal-trigger{:href =>"#search_filter_orders", :class => "waves-effect waves-light btn blue"}
      %i.material-icons.right search
      Filtro


  .row.card.container.modal#search_filter_orders{:style => "width: 800px; height:900px;"}
    = search_form_for @search, url: reports_pending_balance_path do |f|
      .input-field{:class => "col s6"}
        = f.label :client_name_cont, "Cliente"
        = f.text_field :client_name_cont
      .input-field{:class => "col s3"}
        = f.label :created_at_date_gequals, "Desde"
        = f.text_field :created_at_date_gequals,
                       :class => "datepicker_all"
      .input-field{:class => "col s3"}
        = f.label :created_at_date_lequals, "Hasta"
        = f.text_field :created_at_date_lequals,
                       :class => "datepicker_all"

        = f.submit "Buscar", :class => "waves-effect waves-light btn blue",
                              :style => "left: 15px; bottom: 5px;"


  %br


  -#
  -# .container{:style => "margin: 0 auto;"}
  -#
  -#   %a.right{:href =>"#", :class => "waves-effect waves-light btn blue"}
  -#     %i.material-icons.right print
  -#     Imprimir
  -# %br
  -#   %br


    -# .row.card.container.modal#search_filter_orders{:style => "width: 800px; height:900px;"}
    -#   = search_form_for @search, url: accountability_index_path do |f|
    -#     .input-field{:class => "col s6"}
    -#       = f.label :client_name_cont, "Cliente"
    -#       = f.text_field :client_name_cont
    -#     .input-field{:class => "col s3"}
    -#       = f.label :created_at_date_gequals, "Desde"
    -#       = f.text_field :created_at_date_gequals,
    -#                      :class => "datepicker_all"
    -#     .input-field{:class => "col s3"}
    -#       = f.label :created_at_date_lequals, "Hasta"
    -#       = f.text_field :created_at_date_lequals,
    -#                      :class => "datepicker_all"
    -#
    -#     .input-field.col.s6
    -#       = f.select( :state_cont, options_for_select([[""],
    -#                                               ["En Proceso", {class: 'circle', "data-icon" => "/assets/blue.png"}],
    -#                                               ["Urgente", {class: 'circle', "data-icon" => "/assets/red.png"}],
    -#                                               ["En Prueba", {class: 'circle', "data-icon" => "/assets/orange.png"}],
    -#                                               ["Facturada - Pendiente", {class: 'circle', "data-icon" => "/assets/purple.png"}],
    -#                                               ["Facturada - Pago", {class: 'circle', "data-icon" => "/assets/green.png"}],
    -#                                               ["Anulada", {class: 'circle', "data-icon" => "/assets/null.png"}]],
    -#                                               disabled: "Elige el Estado"), class: "icons" )
    -#
    -#     = f.submit "Buscar", :class => "waves-effect waves-light btn blue",
    -#                           :style => "left: 15px; bottom: 5px;"





  .row.container.card{:style => "margin: 0 auto;"}
    %table.centered.highlight#orders_t
      %thead
        %tr
          -# %th Orden No.
          %th Cliente
          -# %th No. Factura
          -# %th Fecha  de Entrada
          -#%th Fecha  de Entrega
          -# %th Estado
          -# %th Monto RD$
          %th Balance RD$
          -# %th Nota Del Cliente
          -# %th Otras Notas
          %th Ver



      %tbody
        - @sales.each do |sale|
          - unless sale.invoice_number == nil
            %tr
              -# %td= sale.id
              %td= sale.client.name
              -# %td= sale.invoice_number.id
              -# %td= sale.created_at.strftime("%d/%m/%Y")
              -#%td= order.order_date
              -# %td= sale.state
              -# %td= "$#{number_to_currency(sale.order_total - sale.discount_amount, :format => "%u%n", :unit => '',:delimiter => ',',:separator => '.')}"
              %td= "$#{number_to_currency(sale.remaining_amount - sale.discount_amount, :format => "%u%n", :unit => '',:delimiter => ',',:separator => '.')}"
              %td.btn-group
                %a{:href => sale_path(sale), :class => "waves-effect waves-light btn-floating blue tooltipped", "data-tooltip" => "Ver", "data-position" => "top"}
                  %i.material-icons.right search



  -# %td= order.client_note
            -# %td= order.other_note



      -# %br
      -# .div
      -#   %ul.pagination{:style => "margin: 0 auto; text-align: right;"}
      -#     %li.disabled
      -#       %a{:href => "#!"}
      -#         %i.material-icons chevron_left
      -#     %li.active
      -#       %a{:href => "#!"} 1
      -#     %li.waves-effect
      -#       %a{:href => "#!"} 2
      -#     %li.waves-effect
      -#       %a{:href => "#!"} 3
      -#     %li.waves-effect
      -#       %a{:href => "#!"}
      -#         %i.material-icons chevron_right

  %br




  -# = link_to 'New Order', new_order_path
  -# END OF MAIN

  -# FOOTER

  %footer.page-footer
    = render :partial => 'layouts/footer'
  -# END OF FOOTER